#!/usr/bin/env bash
# to install pandoc for md to pdf convert with apt use:
# sudo apt-get install pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

while getopts d: flag
do
    case "${flag}" in
        d) DATERANGE=${OPTARG};;
    esac
done

unzip "Export*"
FILENAME="Dreams $DATERANGE.md"
touch dreams

for f in $(ls -tr | grep md); do cat $f; echo; echo; done >> dreams

sed -i -e '/Created:/d' -e '/Tags:/d' dreams
sed -i 's/# Dream/#### Dream/' dreams
sed -i '/^$/N;/^\n$/D' dreams

echo "### Luke's Dreams $DATERANGE" > "$FILENAME"
cat dreams >> "$FILENAME"
rm dreams

IFS=$SAVEIFS
